// ══════════════════════════════════════════
//  SKILLIU — biblioteca-dados.js
//  Catálogo da vitrine. Só o ebook com "real:true" existe de verdade no
//  Supabase (Robótica Descomplicada) — os outros são pra preencher a
//  vitrine e mostrar como fica quando o catálogo estiver completo.
//  Quando cadastrar os outros de verdade no Supabase, é só apagar o
//  "real:false" e trocar pela busca real (ver biblioteca-ebook.js).
// ══════════════════════════════════════════

const CATALOGO_EBOOKS = [
  // ── Grátis ──
  {
    id: 'robotica-descomplicada',
    titulo: 'Robótica Descomplicada',
    categoria: 'Robótica',
    preco: 0,
    capa: 'fotos/ebook-robotica.png',
    descricaoCurta: 'O guia que já ajudou centenas de professores a começar com robótica sem laboratório.',
    descricaoLonga: 'Um passo a passo prático pra levar robótica pra sala de aula mesmo sem infraestrutura especial. Sequências didáticas prontas, alinhadas à BNCC, pensadas pra funcionar com o que a escola já tem.',
    real: true,
  },
  {
    id: 'pensamento-computacional',
    titulo: 'Primeiros Passos no Pensamento Computacional',
    categoria: 'Pensamento Computacional',
    preco: 0,
    capa: null,
    descricaoCurta: 'Introdução leve aos quatro pilares do pensamento computacional, com atividades desplugadas.',
    descricaoLonga: 'Um material introdutório pra quem quer trazer lógica de programação pra sala de aula sem precisar de computador. Atividades desplugadas, prontas pra aplicar em qualquer disciplina.',
    real: false,
  },
  {
    id: 'guia-avaliacao-projetos',
    titulo: 'Guia Rápido de Avaliação por Projetos',
    categoria: 'Avaliação',
    preco: 0,
    capa: null,
    descricaoCurta: 'Modelos práticos de rubricas pra avaliar projetos STEAM sem virar bagunça.',
    descricaoLonga: 'Rubricas prontas e adaptáveis pra avaliar projetos interdisciplinares, com critérios claros pra cada etapa — da ideia à apresentação final.',
    real: false,
  },

  // ── Pagos ──
  {
    id: 'dicionario-sky',
    titulo: 'Dicionário SKY',
    categoria: 'Referência',
    preco: 29.9,
    capa: 'fotos/ebook-dicionario.png',
    descricaoCurta: 'Todos os termos do universo STEAM e SKY explicados em linguagem simples.',
    descricaoLonga: 'Um dicionário de bolso com todos os termos técnicos do universo STEAM e da metodologia SKY, explicados em linguagem acessível pra qualquer professor, mesmo sem background técnico.',
    real: false,
  },
  {
    id: 'skilliblocks-na-pratica',
    titulo: 'SkilliBlocks na Prática',
    categoria: 'Programação',
    preco: 39.9,
    capa: 'fotos/ebook-skilliblocks.png',
    descricaoCurta: '20 planos de aula prontos usando o método SkilliBlocks em sala.',
    descricaoLonga: 'Planos de aula completos, semana a semana, pra aplicar o SkilliBlocks com sua turma — incluindo variações pra diferentes idades e tempos de aula.',
    real: false,
  },
  {
    id: 'projetos-papelao',
    titulo: '20+ Projetos com Papelão',
    categoria: 'Mão na massa',
    preco: 24.9,
    capa: 'fotos/ebbok-papelao.png',
    descricaoCurta: 'Mais de 20 projetos STEAM usando só papelão e materiais recicláveis.',
    descricaoLonga: 'Uma coletânea de projetos de baixo custo, feitos com papelão e materiais recicláveis, pra turmas de todas as idades — sem precisar de nenhum investimento em kits.',
    real: false,
  },
  {
    id: 'robotica-sucata',
    titulo: 'Robótica Avançada com Sucata',
    categoria: 'Robótica',
    preco: 34.9,
    capa: null,
    descricaoCurta: 'Motores, sensores e circuitos simples usando sucata eletrônica.',
    descricaoLonga: 'Pra quem já passou do básico: como montar mecanismos com motores e sensores usando sucata eletrônica, com segurança e baixo custo.',
    real: false,
  },
  {
    id: 'steam-infantil',
    titulo: 'STEAM na Educação Infantil',
    categoria: 'Educação Infantil',
    preco: 27.9,
    capa: null,
    descricaoCurta: 'Atividades STEAM adaptadas pra turmas de 4 a 6 anos.',
    descricaoLonga: 'Atividades sensoriais e exploratórias que introduzem conceitos de ciência, tecnologia e matemática de um jeito lúdico, pensadas pra primeira infância.',
    real: false,
  },
  {
    id: 'programacao-desplugada',
    titulo: 'Programação Desplugada',
    categoria: 'Pensamento Computacional',
    preco: 22.9,
    capa: null,
    descricaoCurta: 'Ensine lógica de programação sem usar nenhuma tela.',
    descricaoLonga: 'Jogos e dinâmicas de mesa que ensinam sequenciamento, loops e condicionais sem precisar de computador ou tablet.',
    real: false,
  },
  {
    id: 'maker-space',
    titulo: 'Maker Space em Sala de Aula',
    categoria: 'Mão na massa',
    preco: 32.9,
    capa: null,
    descricaoCurta: 'Como montar um cantinho maker mesmo em salas pequenas.',
    descricaoLonga: 'Um guia de organização de espaço e materiais pra criar um cantinho maker funcional, mesmo em escolas com pouco espaço físico ou orçamento.',
    real: false,
  },
  {
    id: 'avaliacao-formativa-steam',
    titulo: 'Avaliação Formativa em STEAM',
    categoria: 'Avaliação',
    preco: 26.9,
    capa: null,
    descricaoCurta: 'Como acompanhar o progresso do aluno ao longo de um projeto.',
    descricaoLonga: 'Ferramentas de acompanhamento contínuo pra observar o desenvolvimento do aluno durante o projeto, não só no resultado final.',
    real: false,
  },
  {
    id: 'ciencia-dados-iniciantes',
    titulo: 'Ciência de Dados pra Iniciantes',
    categoria: 'Tecnologia',
    preco: 37.9,
    capa: null,
    descricaoCurta: 'Introdução a gráficos, tabelas e leitura de dados pro ensino médio.',
    descricaoLonga: 'Conceitos introdutórios de ciência de dados aplicados a problemas do dia a dia, com atividades adaptadas pra turmas de ensino médio.',
    real: false,
  },
  {
    id: 'sustentabilidade-steam',
    titulo: 'Projetos de Sustentabilidade STEAM',
    categoria: 'Sustentabilidade',
    preco: 29.9,
    capa: null,
    descricaoCurta: 'Projetos que unem meio ambiente, tecnologia e comunidade local.',
    descricaoLonga: 'Projetos interdisciplinares que conectam sustentabilidade, tecnologia simples e impacto na comunidade ao redor da escola.',
    real: false,
  },
  {
    id: 'robotica-sensores',
    titulo: 'Robótica com Sensores',
    categoria: 'Robótica',
    preco: 41.9,
    capa: null,
    descricaoCurta: 'Sensores de luz, distância e temperatura em projetos guiados.',
    descricaoLonga: 'Projetos guiados usando sensores simples de luz, distância e temperatura, com explicação de como cada um funciona por trás da montagem.',
    real: false,
  },
  {
    id: 'feiras-ciencias',
    titulo: 'Feiras de Ciências Passo a Passo',
    categoria: 'Eventos escolares',
    preco: 25.9,
    capa: null,
    descricaoCurta: 'Do planejamento à apresentação: organize a feira de ciências da escola.',
    descricaoLonga: 'Um roteiro completo pra organizar a feira de ciências da escola, do cronograma de preparação até o dia da apresentação pros pais.',
    real: false,
  },
];
